### PR TITLE
feat(transactional): adds supports propagation mode

### PR DESCRIPTION
**Pull request by merandr**
Adds the "SUPPORTS" propagation mode (inspired by Spring "SUPPORTS" transaction propagation behavior).

### CODE REVIEW

**Comment by Papooch** [comment]
I deliberately left this option out, but maybe you can enlighten me. How is it different to not decorating the method at all?

**Comment by lucas-gregoire** [comment]
Hello @Papooch 👋 ,

I recently came across a use case where the "SUPPORTS" propagation mode would be really useful. In my project, I’m working in a CQRS context with `@nestjs/cqrs`, where I’ve extended the `CommandBus`, `QueryBus`, and `EventBus` to always wrap handler execution with `withTransaction`.

Currently, the QueryBus runs with `NOT_SUPPORTED` by default, while the CommandBus and EventBus run with `REQUIRED`. My setup allows me to override these default values for specific handlers when necessary.

However, I’ve reached the limits of this setup, and using the SUPPORTS mode could unlock the flexibility I need.
For example, if a command opens a transaction to write new data, and an event handler is executed within the same transaction and calls a query to retrieve other data, having `NOT_SUPPORTED` on the QueryBus prevents the query from accessing the uncommitted data.

Using the `SUPPORTS` propagation mode on the QueryBus could resolve this issue by allowing the query to run within an existing transaction if one is active, while still allowing it to run outside of a transaction when needed. What do you think?

**Comment by Papooch** [comment]
Thank you for the specific example.

Now that I think about it, _generally_ if you override the default behavior, which is not using the decorator at all, there probably needs to be an option to _explicitly_ bring the original default back, which is currently impossible.

Would you like to re-open the PR?

**Comment by lucas-gregoire** [comment]
I reopened the PR here #219

**Pull request closed without merging**
