### PR TITLE
feat(drizzle): add basic support for drizzle-orm postgres

### PR DESCRIPTION
**Pull request by fjanicki**
I still need to add a test suite but this should cover the basics of what's needed for Drizzle-ORM

### CODE REVIEW

**Comment by Papooch** [comment]
Thanks for the PR. I can see that you hard-coded only Postgres types. Do you think you could generalize it for any database that drizzle supports? In a similar manner that the Kysely adapter is implemented - using a generic argument for the database type. I am not sure to what extent is that possible, but I'd rather not lock the support for Postgres only.

**Comment by fjanicki** [comment]
I can take a look but this is the only adapter I've been using.

**Comment by Papooch** [comment]
I understand - that's why I encourage people to build their own specific adapters that cover their needs, because it is pretty straightforward.

But if this library should provide a ready-made adapter for a specific ORM / query builder, then it should not be tied to only a subset of (or just a single) supported databases.

**Comment by fjanicki** [comment]
Yeah it makes sense. I'll look into how it's done with Kysely. Just a quick question about how to handle dependencies. Since drizzle requires the installation of the underlying library (pg, postgresjs, mongodb, etc...) would that be a peer dependency? I would prefer to avoid having to install all the libs when someone pulls this library and only use whatever they need. How do you handle this case in this kind of lib? I never had to do this before so i'm not 100% sure.

**Comment by Papooch** [comment]
I fond a bit of free time and had a go at it myself: https://github.com/Papooch/nestjs-cls/pull/180

At first, it was really challenging, because drizzle doesn't really provide a base type (or a common interface) for all the different client types - they're just a bare class.

But it turns out, you don't even need a base type - all that is needed is to know what the basic signature of the `transaction` method is and you're able to extract options out of it.

I don't want your effort to go unnoticed, so I'll go ahead and merge your PR to my branch and base my changes on top of yours, if you agree.

**Pull request merged**
